/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwipeRouteRouteImport } from './routes/swipe/route'
import { Route as ReelsRouteRouteImport } from './routes/reels/route'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as PlacesRouteRouteImport } from './routes/places/route'
import { Route as MapRouteRouteImport } from './routes/map/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as ProfileSettingsRouteRouteImport } from './routes/profile/settings/route'
import { Route as DemoTanstackQueryRouteRouteImport } from './routes/demo/tanstack-query/route'

const SwipeRouteRoute = SwipeRouteRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRouteRoute = ReelsRouteRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRouteRoute = PlacesRouteRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRouteRoute = MapRouteRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRouteRoute = ProfileSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const DemoTanstackQueryRouteRoute = DemoTanstackQueryRouteRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/map': typeof MapRouteRoute
  '/places': typeof PlacesRouteRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/reels': typeof ReelsRouteRoute
  '/swipe': typeof SwipeRouteRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRouteRoute
  '/profile/settings': typeof ProfileSettingsRouteRoute
}
export interface FileRoutesByTo {
  '/map': typeof MapRouteRoute
  '/places': typeof PlacesRouteRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/reels': typeof ReelsRouteRoute
  '/swipe': typeof SwipeRouteRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRouteRoute
  '/profile/settings': typeof ProfileSettingsRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/map': typeof MapRouteRoute
  '/places': typeof PlacesRouteRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/reels': typeof ReelsRouteRoute
  '/swipe': typeof SwipeRouteRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRouteRoute
  '/profile/settings': typeof ProfileSettingsRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/map'
    | '/places'
    | '/profile'
    | '/reels'
    | '/swipe'
    | '/demo/tanstack-query'
    | '/profile/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/map'
    | '/places'
    | '/profile'
    | '/reels'
    | '/swipe'
    | '/demo/tanstack-query'
    | '/profile/settings'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/places'
    | '/profile'
    | '/reels'
    | '/swipe'
    | '/demo/tanstack-query'
    | '/profile/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  MapRouteRoute: typeof MapRouteRoute
  PlacesRouteRoute: typeof PlacesRouteRoute
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  ReelsRouteRoute: typeof ReelsRouteRoute
  SwipeRouteRoute: typeof SwipeRouteRoute
  DemoTanstackQueryRouteRoute: typeof DemoTanstackQueryRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swipe': {
      id: '/swipe'
      path: '/swipe'
      fullPath: '/swipe'
      preLoaderRoute: typeof SwipeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteRouteChildren {
  ProfileSettingsRouteRoute: typeof ProfileSettingsRouteRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileSettingsRouteRoute: ProfileSettingsRouteRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  MapRouteRoute: MapRouteRoute,
  PlacesRouteRoute: PlacesRouteRoute,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  ReelsRouteRoute: ReelsRouteRoute,
  SwipeRouteRoute: SwipeRouteRoute,
  DemoTanstackQueryRouteRoute: DemoTanstackQueryRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
