/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a user profile */
        post: operations["UserProfileController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user profile by id */
        get: operations["UserProfileController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/poi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all POIs */
        get: operations["PoiController_findAll"];
        put?: never;
        /** Create a new POI */
        post: operations["PoiController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/poi/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a POI by UUID */
        get: operations["PoiController_findOne"];
        /** Update a POI */
        put: operations["PoiController_update"];
        post?: never;
        /** Delete a POI */
        delete: operations["PoiController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/category/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a category by id */
        get: operations["CategoryController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all categories */
        get: operations["CategoryController_findAll"];
        put?: never;
        /** Create a new category */
        post: operations["CategoryController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recommendations based on user preferences */
        get: operations["RecommendationController_getRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/poi-decision/user/{userProfileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all decisions by user profile */
        get: operations["PoiDecisionController_getByUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/poi-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new POI decision */
        post: operations["PoiDecisionController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChoiceDto: {
            /**
             * @description Category identifier as UUID
             * @example 8a49f1b5-9a42-4a1f-9c8e-3f6f5c9f1a2b
             */
            category_id?: string;
            /**
             * @description Choice code as string
             * @example 1
             */
            choice?: string;
            /**
             * @description Category weight as number
             * @example 1
             */
            categoryWeight?: number;
        };
        CreateUserProfileDto: {
            /**
             * @description User choices payload as an array of choices
             * @example [
             *       {
             *         "category_id": "8a49f1b5-9a42-4a1f-9c8e-3f6f5c9f1a2b",
             *         "choice": "1"
             *       },
             *       {
             *         "category_id": "3c2a7f12-5d3e-4b9a-8e6f-2b1c9d8f7a6e",
             *         "choice": "2"
             *       }
             *     ]
             */
            choices?: components["schemas"]["ChoiceDto"][];
        };
        CreatePoiDto: {
            /**
             * @description Name of the POI
             * @example Historic City Center
             */
            name: string;
            /**
             * @description Short description of the POI
             * @example Beautiful historic center with medieval architecture
             */
            shortDescription: string;
            /**
             * @description Category UUID
             * @example 7987b9c5-7416-432d-ad61-71ebf143725f
             */
            categoryId: string;
            /**
             * @description Long description of the POI
             * @example The historic city center features well-preserved medieval architecture, cobblestone streets, and numerous cultural landmarks dating back to the 14th century.
             */
            longDescription: string;
            /**
             * @description URL to the image of the POI
             * @example https://example.com/images/poi.jpg
             */
            imageUrl: string;
            /**
             * @description Popularity score (0-100)
             * @example 85
             */
            popularity: number;
            /**
             * @description Location coordinates (x, y)
             * @example 18
             */
            locationX: number;
            /**
             * @description Y coordinate (latitude)
             * @example 53
             */
            locationY: number;
        };
        PoiResponseDto: {
            /**
             * @description Unique identifier
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            uuid: string;
            /**
             * @description Name of the POI
             * @example Historic City Center
             */
            name: string;
            /**
             * @description Short description of the POI
             * @example Beautiful historic center with medieval architecture
             */
            shortDescription: string;
            /**
             * @description Long description of the POI
             * @example The historic city center features well-preserved medieval architecture...
             */
            longDescription: string;
            /**
             * @description URL to the image of the POI
             * @example https://example.com/images/poi.jpg
             */
            imageUrl: string;
            /**
             * @description Popularity score (0-100)
             * @example 85
             */
            popularity: number;
            /**
             * @description X coordinate (longitude)
             * @example 18
             */
            locationX: number;
            /**
             * @description Y coordinate (latitude)
             * @example 53
             */
            locationY: number;
        };
        UpdatePoiDto: {
            /**
             * @description Name of the POI
             * @example Historic City Center
             */
            name?: string;
            /**
             * @description Short description of the POI
             * @example Beautiful historic center with medieval architecture
             */
            shortDescription?: string;
            /**
             * @description Long description of the POI
             * @example The historic city center features well-preserved medieval architecture...
             */
            longDescription?: string;
            /**
             * @description URL to the image of the POI
             * @example https://example.com/images/poi.jpg
             */
            imageUrl?: string;
            /**
             * @description Popularity score (0-100)
             * @example 85
             */
            popularity?: number;
            /**
             * @description Location coordinates (x, y)
             * @example 18
             */
            locationX?: number;
            /**
             * @description Y coordinate (latitude)
             * @example 53
             */
            locationY?: number;
        };
        CategoryEntity: Record<string, never>;
        CreateCategoryDto: {
            /**
             * @description Human-friendly category name
             * @example Sports
             */
            name: string;
            /**
             * @description Publicly accessible URL to the category image
             * @example https://picsum.photos/200/300
             */
            image_url: string;
        };
        PoiDecisionResponseDto: {
            /** @description Decision UUID */
            uuid: string;
            /** @description POI UUID */
            poiId: string;
            /** @description User Profile UUID */
            userProfileId: string;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createAt: string;
            /**
             * Format: date-time
             * @description Last modified timestamp
             */
            modifiedAt: string;
            /** @description Decision value */
            decision: boolean;
            /** @description Embedded POI object */
            poi?: components["schemas"]["PoiResponseDto"];
            /** @description Distance from provided coordinates to POI (meters) */
            distanceMeters?: number;
        };
        CreatePoiDecisionDto: {
            /**
             * @description POI UUID
             * @example 94e1e0db-294e-4109-b11c-9e33d3fd6174
             */
            poiId: string;
            /**
             * @description User Profile UUID
             * @example a3def291-1cda-4cdc-ba1a-8b0d121be858
             */
            userProfileId: string;
            /**
             * @description Decision value
             * @example true
             */
            decision: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UserProfileController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Payload for creating a user profile */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserProfileDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserProfileController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User profile id (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PoiController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all POIs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoiResponseDto"][];
                };
            };
        };
    };
    PoiController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePoiDto"];
            };
        };
        responses: {
            /** @description POI created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoiResponseDto"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PoiController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description POI found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoiResponseDto"];
                };
            };
            /** @description POI not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PoiController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePoiDto"];
            };
        };
        responses: {
            /** @description POI updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoiResponseDto"];
                };
            };
            /** @description POI not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PoiController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description POI deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description POI not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoryController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category ID (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEntity"];
                };
            };
        };
    };
    CategoryController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEntity"][];
                };
            };
        };
    };
    CategoryController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Payload for creating a category */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEntity"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecommendationController_getRecommendations: {
        parameters: {
            query: {
                userId: string;
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recommendations fetched successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoiResponseDto"][];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PoiDecisionController_getByUser: {
        parameters: {
            query?: {
                /** @description Current user latitude */
                latitude?: number;
                /** @description Current user longitude */
                longitude?: number;
            };
            header?: never;
            path: {
                userProfileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of decisions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoiDecisionResponseDto"][];
                };
            };
        };
    };
    PoiDecisionController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePoiDecisionDto"];
            };
        };
        responses: {
            /** @description Decision created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoiDecisionResponseDto"];
                };
            };
        };
    };
}
